# Generated by Django 3.1 on 2020-08-13 10:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merchentdb',
            fields=[
                ('merch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('merch_reggno', models.CharField(default='', max_length=500)),
                ('merch_shop', models.CharField(default='', max_length=500)),
                ('merch_address', models.CharField(default='', max_length=500)),
                ('merch_phone', models.CharField(default='', max_length=500)),
                ('merch_city', models.CharField(default='', max_length=500)),
                ('merch_state', models.CharField(default='', max_length=500)),
                ('merch_zip', models.CharField(default='', max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('merch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=500)),
                ('address', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=500)),
                ('state', models.CharField(default='', max_length=500)),
                ('zip_code', models.CharField(default='', max_length=500)),
                ('phone', models.CharField(default='', max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_category', models.CharField(default='', max_length=500)),
                ('prod_subcategory', models.CharField(default='', max_length=500)),
                ('prod_name', models.CharField(default='', max_length=500, unique=True)),
                ('prod_desc', models.CharField(default='', max_length=500)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=500000)),
                ('image', models.ImageField(upload_to='IMAGES/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ownerprod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.merchentdb')),
            ],
        ),
        migrations.CreateModel(
            name='Orderupdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='', null=True)),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(verbose_name=datetime.datetime(2020, 8, 13, 10, 47, 44, 451918, tzinfo=utc))),
                ('custorders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('quantity', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=5000)),
                ('cust_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='store.Finalorder', to='store.Orderitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='orderitems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orderitem'),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
        migrations.AlterUniqueTogether(
            name='finalorder',
            unique_together={('orderitems', 'orders')},
        ),
    ]
