# Generated by Django 3.1 on 2020-08-13 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200813_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalorder',
            name='cust',
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(verbose_name=datetime.datetime(2020, 8, 13, 10, 48, 36, 579342, tzinfo=utc)),
        ),
    ]
