# Generated by Django 3.1 on 2020-08-14 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200813_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(verbose_name=datetime.datetime(2020, 8, 14, 10, 36, 45, 166839, tzinfo=utc)),
        ),
    ]
