# Generated by Django 3.1 on 2020-08-22 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200814_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(verbose_name=datetime.datetime(2020, 8, 22, 14, 12, 45, 419344, tzinfo=utc)),
        ),
    ]
