# Generated by Django 3.1 on 2020-08-22 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200822_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(verbose_name=datetime.datetime(2020, 8, 22, 14, 52, 46, 545641, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price',
            field=models.FloatField(),
        ),
    ]
